tarantula:
  build: .
  command: go run /app/src/github.com/tarantula/start.go
  ports:
    - "8080:8080"
    - "8081:8081"
  environment:
    ENV: prod
  volumes:
    - /home/pprofessi/projects/go/src/github.com/tarantula:/app/src/github.com/tarantula
  #links:
  #  - db:db

db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: tarantula
    MYSQL_DATABASE: tarantula
    MYSQL_USER: tarantula
    MYSQL_PASSWORD: tarantula
  volumes:
      - ./config/devdata:/var/lib/mysql 
