tarantula:
  build: .
  command: server
  ports:
    - "9999:9999"
  volumes:
    - ./:/app/tarantula
  links:
    - db:db
  environment:
    TARANTULA_CONF: /app/tarantula/tarantula_config_toml.conf

db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: tarantula
    MYSQL_DATABASE: tarantula
    MYSQL_USER: tarantula
    MYSQL_PASSWORD: tarantula

