Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets
  InstanceType:
    Type: String
    Description: Flavor
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH Key
  InstanceSecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Groups
  ELBSecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Groups
  SSLCertificate:
    Type: String
    Description: SSL Certificate to allow https connection from tarantula-group.me 
  AmiId:
    Type: String
    Description: ID of ami that will be used


Resources:
  InstanceProxyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        "Fn::Base64":
          !Sub |
           #!/bin/bash
           bash /home/ec2-user/start.sh
           docker pull pabloncio/tarantula-proxy-prod
           nohup docker run -p 8080:8080 -e "ENV=prod" pabloncio/tarantula-proxy-prod > /var/log/tarantula.log &
      AssociatePublicIpAddress: true
      ImageId: 
        Ref: AmiId
      InstanceType:
        Ref: InstanceType
      SecurityGroups:
        Ref: InstanceSecurityGroups
      KeyName:
        Ref: KeyName

  InstanceProxyAutoscalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LoadBalancerNames: 
      - Ref: InstanceProxyElasticLoadBalancer
      LaunchConfigurationName:
        Ref: InstanceProxyLaunchConfiguration
      MinSize: '1'
      MaxSize: '1'
      VPCZoneIdentifier:
        Ref: Subnets
      Tags:
      - Key: Name
        Value: tarantula-proxy
        PropagateAtLaunch: true

  InstanceProxyElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties: 
      LoadBalancerName: tarantula-proxy
      Scheme: internet-facing
      Subnets:
        Ref: Subnets
      SecurityGroups:
        Ref: ELBSecurityGroups
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
      Listeners:
      - LoadBalancerPort: 80
        InstancePort: 8080
        Protocol: HTTP
        InstanceProtocol: HTTP
      - LoadBalancerPort: 443
        InstancePort: 8080
        Protocol: HTTPS
        SSLCertificateId : 
          Ref: SSLCertificate
      HealthCheck: 
        Target: HTTP:8080/ping
        HealthyThreshold: 2
        UnhealthyThreshold: 2
        Interval: 5
        Timeout: 4
      Tags:
      - Key: Name
        Value: tarantula-proxy


